name: Publish package to GitHub Packages
on:
  release:
    types: [ created ]
  pull_request:
    branches:
      - master
jobs:
#  publish-linux:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Test
#        run: ./gradlew allTests
#      - name: Publish package
#        run: ./gradlew publish --info
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
#          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
#  publish-macos:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Install Automake
#        run: brew install pkg-config autoconf automake openssl
#      - name: Test
#        run: ./gradlew allTests
#      - name: Publish package
#        run: ./gradlew publish --info
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
#          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  publish-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install mingw64
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install mingw
      - name: Test
        run: ./gradlew allTests
#      - name: Publish package
#        run: ./gradlew publish --info
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
#          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}